<a href="https://colab.research.google.com/github/maheswara1234/praktikum-ml-a11202415716/blob/main/repo2_a11202415716.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import warnings

# Mengabaikan pesan peringatan (warning) saat perhitungan statistik
warnings.filterwarnings('ignore')

class AnalisisDataEPL:
    def __init__(self, file_path):
        """Constructor untuk memuat dan membersihkan dataset"""
        print(f"Mencoba memuat data dari: {file_path}")
        self.df = pd.read_csv(file_path)

        # Membersihkan data: Drop kolom 'Unnamed: 0' dan 'id' yang tidak bermakna numerik
        kolom_dibuang = ['Unnamed: 0', 'id']
        self.df_clean = self.df.drop(columns=[col for col in kolom_dibuang if col in self.df.columns])
        print("Data berhasil dimuat dan dibersihkan dari kolom ID yang tidak perlu.\n")

    def tampilkan_sampel_dan_statistik(self):
        """Menampilkan 5 data teratas dan statistik deskriptif"""
        print("=== 5 Baris Pertama Dataset ===")
        display(self.df_clean.head())

        print("\n=== Statistik Deskriptif (Kolom Numerik) ===")
        display(self.df_clean.describe())

    def deteksi_pencilan_assist(self):
        """Mencari pemain dengan jumlah assist di luar batas wajar (Outlier/Pencilan) menggunakan Tukey's Fences"""
        print("\n=== Pemain dengan Assist Terbanyak (Pencilan/Outlier) ===")

        # Ekstraksi hanya kolom numerik
        df_numeric = self.df_clean.select_dtypes(include=[np.number])

        # Logika Tukey's Fences
        q1 = df_numeric.quantile(0.25)
        q3 = df_numeric.quantile(0.75)
        iqr = q3 - q1

        # Menyelaraskan dataframe untuk operasi boolean
        df_align, iqr_new = df_numeric.align(iqr, axis=1, copy=False, join='outer')
        outlier_filter = (df_numeric < q1 - 1.5 * iqr_new) | (df_numeric > q3 + 1.5 * iqr_new)

        # Menerapkan filter khusus untuk kolom 'assists'
        pemain_assist_tinggi = self.df_clean[outlier_filter['assists']][['player_name', 'assists', 'team_title']]
        pemain_assist_tinggi = pemain_assist_tinggi.sort_values(by=['assists'], ascending=False)

        display(pemain_assist_tinggi)

    def analisis_performa_tim(self):
        """Menganalisis rata-rata gol per tim menggunakan groupby"""
        print("\n=== Rata-Rata Gol Pemain per Tim ===")
        rata_gol = self.df_clean.groupby('team_title')['goals'].mean().sort_values(ascending=False).reset_index()

        # Memperbaiki nama kolom agar lebih rapi
        rata_gol.columns = ['Nama Klub', 'Rata-Rata Gol']
        display(rata_gol)

    def uji_korelasi_pearson(self):
        """Menampilkan matriks korelasi Pearson antar variabel"""
        print("\n=== Matriks Korelasi Pearson ===")

        # Hanya menghitung korelasi pada kolom yang relevan (mengabaikan kolom non-numerik)
        korelasi = self.df_clean.corr(numeric_only=True)
        display(korelasi)

# ==========================================
# BLOK EKSEKUSI UTAMA (Main Program)
# ==========================================

# 1. Menentukan letak file CSV
path_file = "epl-goalScorer(20-21).csv"

# 2. Instansiasi Objek (Membuat alat analisisnya)
analisis_epl = AnalisisDataEPL(path_file)

# 3. Eksekusi metode-metode analisis secara berurutan
analisis_epl.tampilkan_sampel_dan_statistik()
analisis_epl.deteksi_pencilan_assist()
analisis_epl.analisis_performa_tim()
analisis_epl.uji_korelasi_pearson()

Mencoba memuat data dari: epl-goalScorer(20-21).csv
Data berhasil dimuat dan dibersihkan dari kolom ID yang tidak perlu.

=== 5 Baris Pertama Dataset ===

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

=== Statistik Deskriptif (Kolom Numerik) ===

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
count,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000
mean,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,1.668582,1.821450,5.663368,3.455060
std,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,2.909929,2.931176,5.600249,3.376584
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,0.000000,0.074668,1.191391,0.720353
50%,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,0.500000,0.715585,4.252738,2.656397
75%,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,2.000000,1.945799,8.308002,5.254647
max,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,19.000000,19.130183,28.968234,18.323006

=== Pemain dengan Assist Terbanyak (Pencilan/Outlier) ===

                player_name  assists               team_title
0                Harry Kane       14                Tottenham
2           Bruno Fernandes       12        Manchester United
58          Kevin De Bruyne       11          Manchester City
51            Jack Grealish       10              Aston Villa
3             Son Heung-Min       10                Tottenham
6               Jamie Vardy        9                Leicester
15          Marcus Rashford        9        Manchester United
57                 Raphinha        9                    Leeds
41            Jack Harrison        8                    Leeds
83              Pascal Groß        8                 Brighton
49              Timo Werner        8                  Chelsea
281         Aaron Cresswell        8                 West Ham
130  Trent Alexander-Arnold        7                Liverpool
358             Lucas Digne        7                  Everton
32        James Ward-Prowse        7              Southampton
16               Sadio Mané        7                Liverpool
4           Patrick Bamford        7                    Leeds
26          Roberto Firmino        7                Liverpool
204        Andrew Robertson        7                Liverpool
18          Matheus Pereira        6     West Bromwich Albion
22          Raheem Sterling        6          Manchester City
42          Bertrand Traoré        6              Aston Villa
62               Pedro Neto        6  Wolverhampton Wanderers
79             Eberechi Eze        6           Crystal Palace
137          Bernardo Silva        6          Manchester City
211           Said Benrahma        6                 West Ham
495         Vladimir Coufal        6                 West Ham

=== Rata-Rata Gol Pemain per Tim ===

                        Nama Klub  Rata-Rata Gol
0        Arsenal,Newcastle United       8.000000
1                 Manchester City       3.208333
2             Everton,Southampton       3.000000
3             Aston Villa,Chelsea       3.000000
4           Liverpool,Southampton       3.000000
5                       Tottenham       2.750000
6                           Leeds       2.608696
7               Manchester United       2.518519
8                        West Ham       2.478261
9                       Leicester       2.370370
10                      Liverpool       2.370370
11                        Chelsea       2.240000
12                    Aston Villa       2.130435
13                        Arsenal       1.961538
14                 Crystal Palace       1.625000
15                        Everton       1.607143
16                    Southampton       1.555556
17                       Brighton       1.500000
18               Newcastle United       1.384615
19                        Burnley       1.280000
20        Wolverhampton Wanderers       1.222222
21           West Bromwich Albion       1.178571
22                 Chelsea,Fulham       1.000000
23                         Fulham       0.925926
24               Sheffield United       0.666667
25   Arsenal,West Bromwich Albion       0.000000
26               Arsenal,Brighton       0.000000
27  West Bromwich Albion,West Ham       0.000000

=== Matriks Korelasi Pearson ===

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
games,1.000000,0.944591,0.439730,0.463869,0.504168,0.562806,0.599164,0.617867,0.565963,0.160326,0.437110,0.465546,0.726598,0.697196
time,0.944591,1.000000,0.398930,0.411203,0.473555,0.516638,0.529534,0.575065,0.592223,0.186333,0.392631,0.408231,0.703801,0.731377
goals,0.439730,0.398930,1.000000,0.932798,0.617490,0.607330,0.873363,0.567752,0.097151,0.053679,0.971591,0.905710,0.727953,0.290990
xG,0.463869,0.411203,0.932798,1.000000,0.636205,0.627495,0.910214,0.570488,0.093761,0.048815,0.894286,0.979218,0.763909,0.282746
assists,0.504168,0.473555,0.617490,0.636205,1.000000,0.885850,0.721220,0.835299,0.209349,-0.021444,0.587316,0.615503,0.752587,0.473254
xA,0.562806,0.516638,0.607330,0.627495,0.885850,1.000000,0.759568,0.946506,0.243912,0.006284,0.585152,0.611100,0.814487,0.547983
shots,0.599164,0.529534,0.873363,0.910214,0.721220,0.759568,1.000000,0.743370,0.249957,0.073932,0.852989,0.901386,0.843152,0.448197
key_passes,0.617867,0.575065,0.567752,0.570488,0.835299,0.946506,0.743370,1.000000,0.343357,0.022780,0.539726,0.545537,0.807958,0.618754
yellow_cards,0.565963,0.592223,0.097151,0.093761,0.209349,0.243912,0.249957,0.343357,1.000000,0.165064,0.093270,0.089065,0.401884,0.562467
red_cards,0.160326,0.186333,0.053679,0.048815,-0.021444,0.006284,0.073932,0.022780,0.165064,1.000000,0.055542,0.047354,0.104005,0.167660
npg,0.437110,0.392631,0.971591,0.894286,0.587316,0.585152,0.852989,0.539726,0.093270,0.055542,1.000000,0.913496,0.720978,0.284135
npxG,0.465546,0.408231,0.905710,0.979218,0.615503,0.611100,0.901386,0.545537,0.089065,0.047354,0.913496,1.000000,0.763481,0.273090
xGChain,0.726598,0.703801,0.727953,0.763909,0.752587,0.814487,0.843152,0.807958,0.401884,0.104005,0.720978,0.763481,1.000000,0.802073
xGBuildup,0.697196,0.731377,0.290990,0.282746,0.473254,0.547983,0.448197,0.618754,0.562467,0.167660,0.284135,0.273090,0.802073,1.000000